return {
  "williamboman/mason.nvim",
  lazy = false,
  opts = {
    ensure_installed = {
      "bash-debug-adapter",
      "bash-language-server",
      "codespell",
      "css-lsp",
      "delve",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint_d",
      "go-debug-adapter",
      "goimports",
      "golangci-lint",
      "golangci-lint-langserver",
      "golines",
      "gopls",
      "graphql-language-service-cli",
      "html-lsp",
      "jdtls",
      "jq-lsp",
      "json-lsp",
      "jsonlint",
      "lua-language-server",
      "luacheck",
      "markdownlint",
      "node-debug2-adapter",
      "nxls",
      "prettierd",
      "prisma-language-server",
      "rust-analyzer",
      "rustfmt",
      "shfmt",
      "sqlfluff",
      "sqlls",
      "stylua",
      "tailwindcss-language-server",
      "typescript-language-server",
      "vim-language-server",
      "yaml-language-server",
      "yamlfmt",
      "yamllint",
    },
  },
}
