name: "build"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: rckgomz/my-devenv_devcontainer_app:latest
          cacheFrom: rckgomz/my-devenv_devcontainer_app:latest
          push: always
# name: ci
#
# on:
#   push:
#     branches:
#       - "main"
#
# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           context: "{{defaultContext}}:.devcontainer"
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-devenv:latest
#           cache-from: |
#             ${{ secrets.DOCKERHUB_USERNAME }}/my-devenv:cache
#             type=local,src=/tmp/
#           cache-to: |
#             ${{ secrets.DOCKERHUB_USERNAME }}/my-devenv:cache
#             type=local,dest=/tmp/
